class: prophet.Prophet

params:
  weekly_seasonality: true
  yearly_seasonality: true
  daily_seasonality: false
  changepoint_prior_scale: 0.05
  seasonality_mode: multiplicative

forecast:
  horizon: 6
  freq: "D"